### PR TITLE
Update dovi_tool to 2.1.2

### PR DESCRIPTION
**Pull request by lawrencecurtis**
## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

### CODE REVIEW

**Comment by revenz** [comment]
should turn this into a DockerMod

**Comment by lawrencecurtis** [comment]
I’m confused? What script? As far as I’m aware this is the only way to install dovi_tools

**Comment by lawrencecurtis** [comment]
What I’ve edited is the DockerMod

**Comment by revenz** [comment]
lol, sorry thought this was a script being updated.   mixed it up with the ffmpeg script im aware of.

**Pull request merged**
