### PR TITLE
Bug fix - Using folder name in path is ideal for cases of titles with special characters

### PR DESCRIPTION
**Pull request by Feramance**
## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

### CODE REVIEW

**Comment by revenz** [comment]
Update the revision numbers for the files, so they get updated.

**Comment by Feramance** [comment]
Will do

**Comment by lawrencecurtis** [comment]
It might be a good idea to update the comments at the top as they’re not correct

**Comment by Feramance** [comment]
Updated

**Review by revenz — APPROVED** [review]

**Pull request merged**
