### PR TITLE
Mom new script just dropped

### PR DESCRIPTION
**Pull request by Grenwalls**
## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

### CODE REVIEW

**Comment by Grenwalls** [comment]
First time doing this, didn't know what the CLA thing was. But yeah this is a few scripts that are quite simple and realiable to get the native language of a Movie. 
Putting all of them in series (output 2 to next input) basically 100% gets the correct language if it exists.

**Comment by revenz** [comment]
make it a single script, with two boolean inputs
[x] Use Qeueu Data
[x] Use IMDB API

then just call it Radarr - Get Native Language

**Comment by Grenwalls** [comment]
Added the script with bools. It's not done in general, but ah.

**Comment by revenz** [comment]
closing as not a single file

**Pull request closed without merging**
