### PR TITLE
Urgent helper bug fix

### PR DESCRIPTION
**Pull request by Feramance**
## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

### CODE REVIEW

**Comment by Feramance** [comment]
@revenz when can this be merged please? Thanks

**Comment by revenz** [comment]
I havent pulled this yet, because it keeps changing, and also theres a native flow element for this now, what does this script do that that flow element doesnt?

**Comment by Feramance** [comment]
That's a fair point, there will be no more changes, the changes were only missing logic I forgot to move from my manual script to this one. I'd mainly say it benefits anyone still using the script as with the last merge the logic was broken

**Comment by Feramance** [comment]
Actually there is a return specifically to indicate if all audio was deleted or not, and a return if valid audio languages were found, whereas the flow just returns if files were modified and if not

**Pull request merged**
